/* ========================================================================
 * Copyright 2014 preParcial
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 preParcial

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['model/_cursoModel'], function() {
    App.Model.CursoModel = App.Model._CursoModel.extend({

 	validate: function(attrs,options){
            var validationMessage = "";
            
            // TODO No hay cursos en la Universidad que no estén asociados a un programa académico. Cada programa académico tiene un nombre de 4 letras mayúsculas (por ejemplo, ISIS o FISI).
            
            if(attrs.programa.length == 4 )
            {
                var a = attrs.programa.charCodeAt(0);
                var b = attrs.programa.charCodeAt(1);
                var c = attrs.programa.charCodeAt(2);
                var d = attrs.programa.charCodeAt(3);
                
                if(a < 64 || a > 90 || b < 64 || b > 90 || c < 64 || c > 90 || d < 64 || d > 90 )
                {
                    validationMessage = "Los 4 caracteres del programa deben ser letras mayúsculas.";
                }
            }
            else
            {
                validationMessage = "El programa debe ser una cadena de 4 caracteres.";
            }
            
            if(!attrs.name){
                validationMessage = "The name can't be empty.";
            }
            if(validationMessage.length>0){
               return validationMessage;
            }
        }

    });

    App.Model.CursoList = App.Model._CursoList.extend({
        model: App.Model.CursoModel
    });

    return  App.Model.CursoModel;

});